dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
sudo: false
branches:
  except:
    - gh-pages
matrix:
  fast_finish: true
before_install:
  - sudo apt-get -qq update
install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install tox-travis codecov
script:
  - tox
after_success:
  - codecov
