site_name: django-grainy 
site_url: https://github.com/20c/grainy-perms

theme: readthedocs

pages:
  - Home: index.md
  - Install: install.md
  - Settings: settings.md
  - Examples: examples.md

markdown_extensions:
  - markdown_include.include
