# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelB',
            fields=[
                ('modela_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_grainy_test.ModelA')),
            ],
            options={
                'abstract': False,
            },
            bases=('django_grainy_test.modela',),
        ),
        migrations.CreateModel(
            name='ModelC',
            fields=[
                ('modela_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_grainy_test.ModelA')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='django_grainy_test.ModelB')),
            ],
            options={
                'abstract': False,
            },
            bases=('django_grainy_test.modela',),
        ),
        migrations.CreateModel(
            name='ModelD',
            fields=[
                ('modela_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_grainy_test.ModelA')),
            ],
            options={
                'abstract': False,
            },
            bases=('django_grainy_test.modela',),
        ),
    ]
